/*创建序列*/
CREATE SEQUENCE ppm_seq INCREMENT BY 1 START WITH 1000 ;
CREATE SEQUENCE ppm_order_num_seq INCREMENT BY 1 START WITH 100 MAXVALUE 99999 CYCLE;
/*开始删除旧表*/
/*9工序-特性关系表*/
declare
      num   number;
begin
    select count(1) into num from user_tables where table_name = upper('PPM_PRODUCE_CHARAC_LINK') ;
    if num > 0 then
        execute immediate 'drop table PPM_PRODUCE_CHARAC_LINK' ;
    end if;
end;
/*8表单实例表*/
declare
      num   number;
begin
    select count(1) into num from user_tables where table_name = upper('PPM_DATA_INSTANCE') ;
    if num > 0 then
        execute immediate 'drop table PPM_DATA_INSTANCE' ;
    end if;
end;
/*7表单定义表*/
declare
      num   number;
begin
    select count(1) into num from user_tables where table_name = upper('PPM_FORM') ;
    if num > 0 then
        execute immediate 'drop table PPM_FORM' ;
    end if;
end;
/*6产品表*/
declare
      num   number;
begin
    select count(1) into num from user_tables where table_name = upper('PPM_PRODUCT') ;
    if num > 0 then
        execute immediate 'drop table PPM_PRODUCT' ;
    end if;
end;
/*5型号表*/
declare
      num   number;
begin
    select count(1) into num from user_tables where table_name = upper('PPM_MODEL') ;
    if num > 0 then
        execute immediate 'drop table PPM_MODEL' ;
    end if;
end;
/*4特性表*/
declare
      num   number;
begin
    select count(1) into num from user_tables where table_name = upper('PPM_CHARACTERISTIC') ;
    if num > 0 then
        execute immediate 'drop table PPM_CHARACTERISTIC' ;
    end if;
end;
/*3模板-工序关系表*/
declare
      num   number;
begin
    select count(1) into num from user_tables where table_name = upper('PPM_TEMPLATE_WORK_LINK') ;
    if num > 0 then
        execute immediate 'drop table PPM_TEMPLATE_WORK_LINK' ;
    end if;
end;
/*2工序表*/
declare
      num   number;
begin
    select count(1) into num from user_tables where table_name = upper('PPM_WORKING_PROCEDURE') ;
    if num > 0 then
        execute immediate 'drop table PPM_WORKING_PROCEDURE' ;
    end if;
end;
/*1模板表*/
declare
      num   number;
begin
    select count(1) into num from user_tables where table_name = upper('PPM_TEMPLATE') ;
    if num > 0 then
        execute immediate 'drop table PPM_TEMPLATE' ;
    end if;
end;



/*开始创建新表*/

  CREATE TABLE "PPM_TEMPLATE" 
   (	"ID" NUMBER(7,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(100 BYTE), 
	"CREATOR" VARCHAR2(100 BYTE), 
	"CREATETIME" TIMESTAMP (6) DEFAULT sysdate, 
	"UPDATETIME" TIMESTAMP (6) DEFAULT sysdate, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  
  
  CREATE TABLE "PPM_WORKING_PROCEDURE" 
   (	"ID" NUMBER(7,0) NOT NULL ENABLE, 
	"CREATOR" VARCHAR2(100 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"DEL_FLAG" NUMBER(1,0) DEFAULT 0, 
	"CREATETIME" TIMESTAMP (6) DEFAULT sysdate, 
	"UPDATETIME" TIMESTAMP (6) DEFAULT sysdate, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  
  
  
  CREATE TABLE "PPM_TEMPLATE_WORK_LINK" 
   (	"ID" NUMBER(7,0) NOT NULL ENABLE, 
	"CREATOR" VARCHAR2(100 BYTE), 
	"TEMPLATE_ID" NUMBER(7,0), 
	"TW_ID" NUMBER(7,0), 
	"PPM_ORDER" NUMBER(5,0), 
	"CREATETIME" TIMESTAMP (6) DEFAULT sysdate, 
	"UPDATETIME" TIMESTAMP (6) DEFAULT sysdate, 
	"TW_NAME" VARCHAR2(100 BYTE), 
	"TW_CREATOR" VARCHAR2(100 BYTE), 
	"DEL_FLAG" NUMBER(1,0) DEFAULT 0, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "SEQ_TE" FOREIGN KEY ("TEMPLATE_ID")
	  REFERENCES "PPM_TEMPLATE" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "PPM_TEMPLATE_WORK_LINK"."CREATOR" IS '创建者';
   COMMENT ON COLUMN "PPM_TEMPLATE_WORK_LINK"."TEMPLATE_ID" IS '模板id';
   COMMENT ON COLUMN "PPM_TEMPLATE_WORK_LINK"."TW_ID" IS '工序id';
   COMMENT ON COLUMN "PPM_TEMPLATE_WORK_LINK"."PPM_ORDER" IS '排序号';
   COMMENT ON COLUMN "PPM_TEMPLATE_WORK_LINK"."TW_NAME" IS '工序名';
   COMMENT ON COLUMN "PPM_TEMPLATE_WORK_LINK"."TW_CREATOR" IS '工序创建者';

   
  
  CREATE TABLE "PPM_CHARACTERISTIC" 
   (	"ID" NUMBER(7,0) NOT NULL ENABLE, 
	"CREATOR" VARCHAR2(100 BYTE), 
	"TW_ID" NUMBER(7,0), 
	"NAME" VARCHAR2(100 BYTE), 
	"TOTAL" NUMBER(10,0), 
	"COEFFICIENT" NUMBER(3,0), 
	"PPM_ORDER" NUMBER(5,0), 
	"DEL_FLAG" NUMBER(1,0) DEFAULT 0, 
	"CREATETIME" TIMESTAMP (6) DEFAULT sysdate, 
	"UPDATETIME" TIMESTAMP (6) DEFAULT sysdate, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  
  
  CREATE TABLE "PPM_MODEL" 
   (	"ID" NUMBER(7,0) NOT NULL ENABLE, 
	"CREATOR" VARCHAR2(100 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"MODEL_CODE" VARCHAR2(100 BYTE), 
	"CREATETIME" TIMESTAMP (6) DEFAULT sysdate, 
	"UPDATETIME" TIMESTAMP (6) DEFAULT sysdate, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

  
  
  CREATE TABLE "PPM_PRODUCT" 
   (	"ID" NUMBER(7,0) NOT NULL ENABLE, 
	"CREATOR" VARCHAR2(100 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"PRODUCT_CODE" VARCHAR2(100 BYTE), 
	"MODEL_TYPE" VARCHAR2(100 BYTE), 
	"MODEL_ID" VARCHAR2(100 BYTE), 
	"CREATETIME" TIMESTAMP (6) DEFAULT sysdate, 
	"UPDATETIME" TIMESTAMP (6) DEFAULT sysdate, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  

  CREATE TABLE "PPM_FORM" 
   (	"ID" NUMBER(7,0) NOT NULL ENABLE, 
	"CREATOR" VARCHAR2(100 BYTE), 
	"PRODUCT_ID" NUMBER(7,0), 
	"CHARA_ID" NUMBER(7,0), 
	"TW_ID" NUMBER(7,0), 
	"PPM_ORDER" NUMBER(5,0), 
	"BATCH" VARCHAR2(100 BYTE), 
	"QUANTITY" NUMBER(7,0), 
	"CATEGORY" VARCHAR2(100 BYTE), 
	"MODULE_NAME" VARCHAR2(100 BYTE), 
	"PROCEDURE_NAME" VARCHAR2(100 BYTE), 
	"CHARAC_NAME" VARCHAR2(100 BYTE), 
	"CHARAC_QUANTITY" NUMBER(7,0), 
	"KJ" NUMBER(7,0), 
	"LOGO" NUMBER(7,0), 
	"CREATETIME" TIMESTAMP (6) DEFAULT sysdate, 
	"UPDATETIME" TIMESTAMP (6) DEFAULT sysdate, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "PPM_FOREIGN_KEY_5" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "PPM_PRODUCT" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "PPM_FORM"."CREATOR" IS '�';
   COMMENT ON TABLE "PPM_FORM"  IS '琛ㄥ崟瀹氫箟琛�';

   
   
  CREATE TABLE "PPM_DATA_INSTANCE" 
   (	"ID" NUMBER(7,0) NOT NULL ENABLE, 
	"CREATOR" VARCHAR2(100 BYTE), 
	"PRODUCT_ID" NUMBER(7,0), 
	"CHARA_ID" NUMBER(7,0), 
	"DEFECT_NUMBER" NUMBER(7,0), 
	"TW_ID" NUMBER(7,0), 
	"PPM_ORDER" NUMBER(5,0), 
	"BATCH" VARCHAR2(100 BYTE), 
	"QUANTITY" NUMBER(7,0), 
	"CHECK_TYPE" VARCHAR2(100 BYTE), 
	"CHECK_PERSON" VARCHAR2(100 BYTE), 
	"CHECK_PERSON_ID" VARCHAR2(100 BYTE), 
	"CHECK_TIME" TIMESTAMP (6), 
	"PRODUCT_COUNT" NUMBER, 
	"CATEGORY" VARCHAR2(100 BYTE), 
	"MODULE_NAME" VARCHAR2(100 BYTE), 
	"PROCEDURE_NAME" VARCHAR2(100 BYTE), 
	"CHARAC_NAME" VARCHAR2(100 BYTE), 
	"CHARAC_QUANTITY" NUMBER, 
	"CHARAC_PPM" NUMBER, 
	"KJ" NUMBER, 
	"LOGO" NUMBER(10,0), 
	"CHARACTERISTICS_TOTAL" NUMBER(10,0), 
	"PROCEDURE_PPM" NUMBER(10,0), 
	"DEFECT_NUMBER_ITEM" NUMBER(10,0), 
	"DATAINS_MARK" NUMBER(10,0), 
	"CREATETIME" TIMESTAMP (6) DEFAULT sysdate, 
	"UPDATETIME" TIMESTAMP (6) DEFAULT sysdate, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "PPM_FOREIGN_KEY_8" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "PPM_PRODUCT" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "PPM_DATA_INSTANCE"."BATCH" IS '生产批次';
   
   
   
  CREATE TABLE "PPM_PRODUCE_CHARAC_LINK" 
   (	"ID" NUMBER(7,0) NOT NULL ENABLE, 
	"CREATOR" VARCHAR2(100 BYTE), 
	"CREATETIME" TIMESTAMP (6) DEFAULT sysdate, 
	"UPDATETIME" TIMESTAMP (6) DEFAULT sysdate, 
	"PRO_LINK_ID" NUMBER(7,0), 
	"PPM_ORDER" NUMBER(5,0), 
	"TOTAL" NUMBER(10,0), 
	"COEFFICIENT" NUMBER(3,0), 
	"CHARA_NAME" VARCHAR2(100 BYTE), 
	"DEL_FLAG" NUMBER(1,0) DEFAULT 0, 
	 CONSTRAINT "PRIMARY_PCID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FROEIGN_PROLINKID" FOREIGN KEY ("PRO_LINK_ID")
	  REFERENCES "PPM_TEMPLATE_WORK_LINK" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


 
 
 
 
 
 